name: build-docker

on:
  push:
    branches:
      - 'feature/gha_docker_build'

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: xilinx/finn-base
        dockerfile: docker/Dockerfile

